#!/usr/bin/perl

use warnings;

$pi = 3.141592654;

print "Enter radius:";
chomp($radius = <STDIN>);

$circumference = 2 * $radius * $pi;

print "Circumference of a circle with radius $radius is $circumference\n";
