#!/usr/bin/perl

use warnings;

print "Enter first number:";
chomp($num1 = <STDIN>);

print "Enter second number:";
chomp($num2 = <STDIN>);

$product = $num1 * $num2;

print "Product of $num1 and $num2 is $product\n";
