#!/usr/bin/perl

use strict;
use warnings;
use File::Basename;

die "Need 2 arguments, source and destination" unless @ARGV == 2;

my($source, $dest) = @ARGV;

if (-d $dest) {
  $dest .= "/" . basename $source;
}

rename $source, $dest or die "Error moving files!";
