#!/usr/bin/perl

use warnings;

print "Enter the radius: ";
chomp($radius = <STDIN>);

if ($radius < 0) {
    $radius = 0;
}

$pi = 3.141592654;
$circumference  = 2 * $pi * $radius;

print "The circumference of a circle with radius $radius is: $circumference \n";
