#!/usr/bin/perl

use strict;
use warnings;

use feature "say";

my %last_name = qw{
  fred flintstone Wilma Flintstone Barney Rubble
  betty rubble Bamm-Bamm Rubble PEBBLES FLINTSTONE
};

my @keys =
  sort { "\L$last_name{$a}" cmp "\L$last_name{$b}" or "\L$a" cmp "\L$b" }
  keys %last_name;

foreach (@keys) {
    say "$_ $last_name{$_}";
}

