#!/usr/bin/perl

use strict;
use warnings;
use File::Slurp;

die "File must be specified!" if ( !@ARGV );
my @strings = read_file($ARGV[0], chomp => 1);

while (1) {
  print "Enter a regular expression\n";
  chomp (my $regex = <STDIN>);

  last if ( !$regex );

  eval {
    print join "\n", grep /$regex/, @strings;
    print "\n";
  };

  print "Error processing regular expression: $@" if $@;
}
