#!/usr/bin/perl

use warnings;
use strict;

while (<>) {                   # take one input line at a time
	chomp;
	if (/((\ba\b)|\w+a\b)/i) {
		print "Matched: |$`<$&>$'|\n";  # the special match vars
		print "\$1 contains '$1'\n";
	} else {
		print "No match: |$_|\n";
	}
}
