#!/usr/bin/perl

use warnings;
use strict;

while (<>) {                   # take one input line at a time
	chomp;
	if (/(?<word>(\ba\b)|\w+a\b)/i) {
		print "Matched: |$`<$&>$'|\n";  # the special match vars
		print "word contains '$+{word}'\n";
	} else {
		print "No match: |$_|\n";
	}
}
