#!/usr/bin/perl

use strict;
use warnings;

sub total {
  my $sum = 0;

  $sum += $_ foreach(@_);

  $sum;
}

sub average {
  my $avg = 0;

  $avg = &total(@_)/(scalar @_) if(scalar @_);

  $avg;
}

sub above_average {
  my $avg = &average(@_);
  my @ret;

  foreach(@_) {
    push @ret, $_ if($_ > $avg);
  }

  @ret;
}

my @fred = above_average(1..10);
print "\@fred is @fred\n";
print "(Should be 6 7 8 9 10)\n";
my @barney = above_average(100, 1..10);
print "\@barney is @barney\n";
print "(Should be just 100)\n";
