#!/usr/bin/perl

use strict;
use warnings;

use 5.010;

sub greet {
  state @guests;
  my $new_guest = shift;

  if(0 == scalar @guests) {
    print "Hi, $new_guest! You are the first one here!\n";
  }
  else {
    print "Hi, $new_guest! I've seen: @guests\n";
  }

  push @guests, $new_guest;
}

greet( "Fred" );
greet( "Barney" );
greet( "Wilma" );
greet( "Betty" );

