#!/usr/bin/perl

use strict;
use warnings;
use 5.10.0;

my $guess = 101;
my $secret =  int(1 + rand 100);

while (1) {
  say "Take a guess";
  chomp ($guess = <STDIN>);
  last if (!$guess || $guess =~ /quit|exit/i || $guess == $secret);
  say "Too " . ($guess < $secret ? "low" : "high");
}
