#!/usr/bin/perl
## Copyright (C) 2015 by dtj

use warnings;
use strict;

# None of this fixed string rubbish here
print "What do you want to match?\n";
chomp( my $what = <STDIN> );

print "Give me some input\n";
chomp( my $input = <STDIN> );

if ( $input =~ /($what){3}/ ) {
  print "Match!\n";
} else {
  print "No match.\n"
}
